language: java # Define the language
jdk: # Define the execution environments
 - openjdk10
branches: # Execute job only on specific branch commits
 only:
 - main
 - development

before_script: # Run commands
 - cd project # Enter Maven root directory
 - ls -la
script: # Build the project
 - mvn clean package
 - mvn test
after_success: # Notify users about the result
 - echo “Process terminated successfully”